name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: install dependencies
        run: yarn install
      - name: Run build
        run: yarn build
      - name: Detect unwanted changes
        run: |
          git diff --stat --exit-code
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: install dependencies
        run: yarn install
      - name: Run test
        run: yarn test
